# An Informal Argument Model {#informal-argument-model}

**The Global Brain algorithm's core objective is to maximize the impact of the best ideas and arguments.**
We do this by finding the "best" reply to any post to make it its note -- the most helpful context shown alongside it.
But "best" is a tricky term in the realm of arguments and ideas.
What makes an argument "best"?
And how do we even know what an *argument* is if everything is just a post?

[Many attempts have been made](https://en.wikipedia.org/wiki/Argument_map) to formalize debate by creating formal models of claims, propositions, arguments, and other constituents of debate.
We deviate from this approach and propose an **informal argument model**.

**The Global Brain does not require a formal model of belief. It doesn't need posts to be structured as formal propositions or claims. It doesn't need to know if users agree or disagree with posts.**

The only assumptions are:

1. Upvotes and downvotes define a **single dimension** across which content is evaluated and there is a **common understanding** among users about what upvotes and downvotes mean.
2. The direction of Users' votes is **causally related** to their **underlying beliefs** about the topic of the post that we cannot observe (latent variables).

By making these assumptions about the causal relationship between beliefs and votes and then watching how exposure to notes causes changes to votes, we can model underlying beliefs and predict how exposure to a note will cause changes to these beliefs, which will cause changes to other beliefs, and so on.


<!-- NOTES: -->

<!-- Chat Felix/Johannes -->

<!-- also hier geht es ja, darum, dass sich die besten Ideen und Argumente verbreiten und bei den Richtigen Leuten ankommen -->

<!-- Ein großer Teil davon ist überhaupt ein gemeinsames Verständnis davon zu haben, was überhaupt fakten sind -->

<!-- Es geht darum information zu identifizieren, die etwas bewirkt. Bzw zu identifizieren wo es etwas bewirken kann. -->
<!-- It is about identifying information that has an effect. Or rather, identifying where it can have an effect. -->

<!-- --- -->

<!-- exploration/exploitation trade-off -->

<!-- Thompson Sampling -->
